print("The program that prints the multiline string values without using triple quotes")
print("multiline strings using double quotes")
print("=========================================")
print("\n hii\n hello\n how r u???")
print("=========================================")
print("multiine strings using single quotes")
print("=========================================")
print('\n hello\n i am fine\n wt abt u???')
print("=========================================")
