print("This program illustrate the difference between Raw string and Normal string")
print("*****************************************************************")
print("The below line demostrate the example of \"normal string\"")
print("*****************************************************************")
print("Ami:\\solanki")
print("*****************************************************************")
print("The below string demostrate the example of \"raw string\"")
print("*****************************************************************")
print(r"Ami:\\solanki")
